### ISSUE TITLE
Not visable when scrolling

### ISSUE THREAD

**Issue by BolverBlitz** [mickelsonmichael/js-snackbar#81]
On my project the element is always in the given location from when i load the page.
If i scroll and call another element i can´t see it because its all the way up top. (Firefox, Chrome, Edge)
In picture 1 i called many elements while scrolled down. The first 4 aren´t visable at all, the 5th only half.
On your demo page it always is visable and dosn´t care about the scrolling.

[My File](https://github.com/BolverBlitz/SteamkeyWebmanager/blob/main/www-public/index.html)
[Demo Link](https://keys.ebg.pw/)

Picture 1:
![grafik](https://user-images.githubusercontent.com/35345288/175835082-d22f1a68-b9d1-44ed-8955-4f12cddb7d85.png)

**Comment by mickelsonmichael** [comment]
There are a couple solutions to your problem. The basic issue is that, by default, the snackbars will be placed as a child of the `<body>` tag and have an `absolute` positioning. Since the body is scrolling, the snackbars are remaining at the top.

Solution 1: Set the snackbar property `fixed` to `true`

Solution 2: Create an inner container that scrolls, rather than the body

**Comment by BolverBlitz** [comment]
Thank you for the fast answer
